name: Indexer

on:
  schedule:
    - cron: '* 0 * * SUN'

jobs:
  libstd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: roogle-index
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: ./roogle-index/.github/actions/build-rustc/
      - name: Index libstd crates
        run: ../roogle-index/ci/scripts/libstd.sh
        working-directory: rust
      - run: |
          git config user.name "Melchior 1"
          git config user.email "actions@github.com"
          git add .
          git commit -m "libstd: Weekly update"
        working-directory: roogle-index
  rustc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: roogle-index
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: ./roogle-index/.github/actions/build-rustc/
      - name: Index rustc crates
        run: ../roogle-index/ci/scripts/rustc.py
        working-directory: rust
      - run: |
          git config user.name "Balthasar 2"
          git config user.email "actions@github.com"
          git add .
          git commit -m "rustc: Weekly update"
        working-directory: roogle-index
