name: Indexer

on:
  schedule:
    - cron: '* 0 * * SUN'

jobs:
  libstd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: roogle-index
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: ./roogle-index/.github/actions/build-rustc/
      - name: Index libstd crates
        run: ../roogle-index/ci/scripts/libstd.sh
        working-directory: rust
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: roogle-index
          commit_message: "libstd: Weekly update"
          commit_user_name: "Melchior 1"
  rustc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: roogle-index
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: ./roogle-index/.github/actions/build-rustc/
      - name: Index rustc crates
        run: ../roogle-index/ci/scripts/rustc.py
        working-directory: rust
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: roogle-index
          commit_message: "rustc: Weekly update"
          commit_user_name: "Balthasar 2"
